modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "barched_extra_spears"
version = "${version}"
displayName = "barchedES"
authors = "zzik2"
description = '''

'''
logoFile = "assets/barched_extra_spears/icon.png"

[[dependencies.barched_extra_spears]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.barched_extra_spears]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.barched_extra_spears]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.barched_extra_spears]]
modId = "cloth_config"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.barched_extra_spears]]
modId = "barched"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"


[[dependencies.barched_extra_spears]]
modId = "bronze"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"


[[mixins]]
config = "barched_extra_spears.mixins.json"
